"""Periodic maintenance — archive stale entries, merge duplicates, export MEMORY.md.

Runs on schedule (every 7 days or after 2h+ idle).  Manages the
lifecycle: active → stale (30d) → archived (90d).
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone, timedelta
from pathlib import Path

logger = logging.getLogger(__name__)

STALE_DAYS = 30
ARCHIVE_DAYS = 90


def run_curator(mem0_client, skills_dir: str | None = None, export_path: str | None = None) -> dict:
    """Run all curator maintenance tasks.

    Returns a stats dict summarizing changes.
    """
    stats: dict = {
        "stale_marked": 0,
        "archived": 0,
        "merged": 0,
        "exported_entries": 0,
        "errors": [],
    }

    # 1. Mark stale entries
    try:
        stats["stale_marked"] = _mark_stale(mem0_client)
    except Exception as exc:
        stats["errors"].append(f"stale: {exc}")

    # 2. Archive very old entries
    try:
        stats["archived"] = _archive_old(mem0_client)
    except Exception as exc:
        stats["errors"].append(f"archive: {exc}")

    # 3. Export MEMORY.md
    if export_path:
        try:
            stats["exported_entries"] = export_memory_md(mem0_client, export_path)
        except Exception as exc:
            stats["errors"].append(f"export: {exc}")

    # 4. Expire pending queue
    try:
        from coworker.memory.pending import expire_old_items
        expired = expire_old_items()
        stats["pending_expired"] = expired
    except Exception as exc:
        stats["errors"].append(f"pending_expire: {exc}")

    logger.info("Curator run complete: %s", stats)
    return stats


def _mark_stale(mem0_client) -> int:
    """Mark active entries as stale if unused for STALE_DAYS."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=STALE_DAYS)).strftime("%Y-%m-%dT%H:%M:%SZ")
    count = 0
    try:
        results = mem0_client.search(
            query="",
            filters={"state": "active"},
            top_k=200,
        )
        for entry in results:
            last_used = entry.get("metadata", {}).get("last_used", "")
            if last_used and last_used < cutoff:
                mem0_client.update(entry["id"], metadata={"state": "stale"})
                count += 1
    except Exception as exc:
        logger.warning("_mark_stale error: %s", exc)
    if count:
        logger.info("Marked %d entries as stale", count)
    return count


def _archive_old(mem0_client) -> int:
    """Archive entries that have been stale beyond ARCHIVE_DAYS."""
    cutoff = (datetime.now(timezone.utc) - timedelta(days=ARCHIVE_DAYS)).strftime("%Y-%m-%dT%H:%M:%SZ")
    count = 0
    try:
        results = mem0_client.search(
            query="",
            filters={"state": "stale"},
            top_k=200,
        )
        for entry in results:
            last_used = entry.get("metadata", {}).get("last_used", "")
            if last_used and last_used < cutoff:
                mem0_client.update(entry["id"], metadata={"state": "archived"})
                count += 1
    except Exception as exc:
        logger.warning("_archive_old error: %s", exc)
    if count:
        logger.info("Archived %d entries", count)
    return count


def export_memory_md(mem0_client, export_path: str) -> int:
    """Generate a human-readable MEMORY.md from mem0 entries.

    Groups entries by project, then by type.
    Returns count of exported entries.
    """
    path = Path(export_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    projects: dict[str, list[dict]] = {}
    try:
        # Fetch active entries for all projects
        results = mem0_client.search(query="", filters={"state": "active"}, top_k=500)
    except Exception as exc:
        logger.warning("export_memory_md search failed: %s", exc)
        results = []

    for entry in results:
        proj = entry.get("metadata", {}).get("project", "unknown")
        projects.setdefault(proj, []).append(entry)

    lines = [
        "# MEMORY.md — Auto-generated by curator",
        f"> Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC",
        f"> Total entries: {len(results)}",
        "",
        "> ⚠️ This file is a **read-only export** from mem0. Do not edit directly.",
        "",
    ]

    for proj_name in sorted(projects):
        lines.append(f"## Project: {proj_name}")
        lines.append("")
        entries = projects[proj_name]
        # Sort by type then by memory
        entries.sort(key=lambda e: (e.get("metadata", {}).get("type", ""), e.get("memory", "")))

        current_type = None
        for entry in entries:
            etype = entry.get("metadata", {}).get("type", "lesson")
            if etype != current_type:
                current_type = etype
                lines.append(f"### {etype.title()}s")
                lines.append("")
            topic = entry.get("metadata", {}).get("topic", "")
            prefix = f"`{topic}` " if topic else ""
            lines.append(f"- {prefix}{entry.get('memory', '')}")
        lines.append("")

    path.write_text("\n".join(lines))
    logger.info("Exported %d entries to %s", len(results), export_path)
    return len(results)


def generate_report(mem0_client, export_dir: str) -> Path:
    """Generate a curator REPORT.md with metrics summary."""
    report_path = Path(export_dir) / "REPORT.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        active = len(mem0_client.search(query="", filters={"state": "active"}, top_k=1))
        stale = len(mem0_client.search(query="", filters={"state": "stale"}, top_k=1))
        archived = len(mem0_client.search(query="", filters={"state": "archived"}, top_k=1))
    except Exception:
        active = stale = archived = 0

    lines = [
        "# Curator Report",
        f"> Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')} UTC",
        "",
        "## Memory Store",
        f"- Active: ~{active}",
        f"- Stale: ~{stale}",
        f"- Archived: ~{archived}",
        "",
    ]

    report_path.write_text("\n".join(lines))
    return report_path
